In [3]:
import numpy as np  
import numpy.polynomial.legendre as npl
import sympy as sp
from scipy.special import legendre

In [79]:
def Transformation(nodes, weight,a,b):
    nodes=(b-a)/2*nodes+(a+b)/2
    weight=(b-a)/2 *weight
    return (nodes,weight)

In [21]:
def Derivate(f,nodes):
    d=np.zeros(len(nodes))
    for i in range(0,len(nodes)):
        if i==0:
            d[i]=(f(nodes[i+1])-f(nodes[i]))/(nodes[i+1]-nodes[i])
        elif i==(len(nodes)-1):
            d[i]=(f(nodes[i])-f(nodes[i-1]))/(nodes[i]-nodes[i-1])
        else:
            d[i]=(f(nodes[i+1])-f(nodes[i-1]))/(nodes[i+1]-nodes[i-1])
    return d

Probando que funciona la Derivada por la definición de $\frac{f(x+h)-f(x)}{h}$

In [26]:
f= lambda x: x**2
nodes=[0,0.1,0.2,0.25,0.3]

Derivate(f,nodes)

array([0.1 , 0.2 , 0.35, 0.5 , 0.55])

Tengo que ver como crear phi con la funcion legendre y las funciones para derivadas

In [5]:
x = sp.symbols('x')

def P(n, x): 
    if(n == 0):
        return 1 # P0 = 1
    elif(n == 1):
        return x # P1 = x
    else:
        return (((2 * n)-1)*x * P(n-1, x)-(n-1)*P(n-2, x))/float(n)
    
N=4
xvals = np.linspace(-1,1,N+1)

x = sp.symbols('x')

L_n_p = lambda x:sp.diff(sp.simplify(P(N,x)))
L_n = lambda x:sp.simplify(P(N,x))

i=0
phi0=lambda x:((-1)/(N*(N+1)))*((1-x**2)*(L_n_p(x))/((x-xvals[[i]])*(L_n(xvals)[[i]])))
simp0=lambda x:sp.simplify(phi0(x))
dif0=lambda x:sp.simplify(sp.diff(simp0(x)))
print(i,simp0(x))
print(dif0(x))

i=1
phi1=lambda x:((-1)/(N*(N+1)))*((1-x**2)*(L_n_p(x))/((x-xvals[[i]])*(L_n(xvals)[[i]])))
simp1=lambda x:sp.simplify(phi1(x))
dif1=lambda x:sp.simplify(sp.diff(simp1(x)))
print(i,simp1(x))
print(dif1(x))

i=2
phi2=lambda x:((-1)/(N*(N+1)))*((1-x**2)*(L_n_p(x))/((x-xvals[[i]])*(L_n(xvals)[[i]])))
simp2=lambda x:sp.simplify(phi2(x))
dif2=lambda x:sp.simplify(sp.diff(simp2(x)))
print(i,simp2(x))
print(dif2(x))

i=3
phi3=lambda x:((-1)/(N*(N+1)))*((1-x**2)*(L_n_p(x))/((x-xvals[[i]])*(L_n(xvals)[[i]])))
simp3=lambda x:sp.simplify(phi3(x))
dif3=lambda x:sp.simplify(sp.diff(simp3(x)))
print(i,simp3(x))
print(dif3(x))

i=4
phi4=lambda x:((-1)/(N*(N+1)))*((1-x**2)*(L_n_p(x))/((x-xvals[[i]])*(L_n(xvals)[[i]])))
simp4=lambda x:sp.simplify(phi4(x))
dif4=lambda x:sp.simplify(sp.diff(simp4(x)))
print(i,simp4(x))
print(dif4(x))

0 x*(0.875*x**3 - 0.875*x**2 - 0.375*x + 0.375)
3.5*x**3 - 2.625*x**2 - 0.75*x + 0.375
1 -(0.875*x**5 - 1.25*x**3 + 0.375*x)/(0.2890625*x + 0.14453125)
(-3.5*x**5 - 2.1875*x**4 + 2.5*x**3 + 1.875*x**2 - 0.1875)/(0.2890625*x**2 + 0.2890625*x + 0.072265625)
2 2.33333333333333*x**4 - 3.33333333333333*x**2 + 1.0
x*(9.33333333333333*x**2 - 6.66666666666667)
3 -(0.875*x**5 - 1.25*x**3 + 0.375*x)/(0.2890625*x - 0.14453125)
(-3.5*x**5 + 2.1875*x**4 + 2.5*x**3 - 1.875*x**2 + 0.1875)/(0.2890625*x**2 - 0.2890625*x + 0.072265625)
4 x*(0.875*x**3 + 0.875*x**2 - 0.375*x - 0.375)
3.5*x**3 + 2.625*x**2 - 0.75*x - 0.375


In [112]:
i=2
print(i,simp1(x)) #¿Que pasa?

2 2.33333333333333*x**4 - 3.33333333333333*x**2 + 1.0


In [117]:
dif4(x) #aqui pasa igual que arriba

x*(9.33333333333333*x**2 - 6.66666666666667)

In [168]:
def Integrate2(a,b,f,g,weight,nodes):
    fe=ge=np.zeros(len(nodes))

    for i in range(len(nodes)):
        fe[i]=f(nodes[i])
        ge[i]=g(nodes[i])

    return (b-a)/2 *np.array(fe*ge).dot(np.array(weight))

In [176]:
f=lambda x: x**2+1
g=lambda x: 2*x+3
nodes= [-0.77459667 , 0.,          0.77459667] 
weight=[0.55555556, 0.88888889, 0.55555556]

Integrate2(0,1,f,g,weight,nodes)

10.333333391611308

In [57]:
class Cuadrature:
    def __init__(self,nodes=None,weight=None):
        if(list(nodes)!=None):
                self.nodes=nodes
        if(list(weight)!=None):
                self.weight=weight
    def getNodes(self):
        return self.nodes
    def getWeight(self):
        return self.weight
    def getNumPoints(self):
        return len(self.nodes)
    
    def Integrate(self,f):
        return self.Integrate_List(f(np.array(self.nodes)))
    
    def Integrate_List(self,lista):
        if (len(lista)==len(self.weight)):
            return np.array(lista).dot(np.array(self.weight))
        else:
            raise Exception("No has metido correctamente la lista")

Pasar todos los self.nodes y self.weight arriba poniendo num_points.

Intentar integrar bien las funciones o su funcion derivada.

In [83]:
class Legendre(Cuadrature):
    def __init__(self,num_points,a,b):
        Cuadrature.__init__(self,nodes=npl.leggauss(num_points)[0], weight=npl.leggauss(num_points)[1]) 
        self.nodes,self.weight=Transformation(self.nodes, self.weight, a, b)
    def __str__(self):
        return "Nodos: %s \nPesos: %s " %(self.nodes,self.weight)

In [105]:
class Trapecio_Compuesto(Cuadrature): #están considerados los extremos(-1,1)
    def __init__(self,num_points,a,b):
        Cuadrature.__init__(self, nodes=np.array([*np.arange(-1,1,float(2/num_points)).tolist(),1]), weight=np.array([2/(2*num_points),*[2/num_points]*(num_points-1),2/(2*num_points)]))
        self.nodes,self.weight=Transformation(self.nodes, self.weight, a, b)
    def __str__(self):
        return "Nodos: %s \nPesos: %s " %(self.nodes,self.weight)

In [109]:
class Lobato(Cuadrature):
    def __init__(self, num_points,a,b):
        aux=[-1,*sorted(list(legendre(num_points).deriv().r)),1]
        Cuadrature.__init__(self, nodes=np.array(aux), weight=np.array(2/(num_points*(num_points+1)*(legendre(num_points)(aux))**2)))
        self.nodes,self.weight=Transformation(self.nodes, self.weight, a, b)
    def __str__(self):
        return "Nodos: %s \nPesos: %s " %(self.nodes,self.weight)

In [56]:
Cuadrature(3)

TypeError: 'NoneType' object is not iterable

In [121]:
print(Legendre(3,-1,1))

Nodos: [-0.77459667  0.          0.77459667] 
Pesos: [0.55555556 0.88888889 0.55555556] 


In [122]:
print(Legendre(3,0,3))

Nodos: [0.338105 1.5      2.661895] 
Pesos: [0.83333333 1.33333333 0.83333333] 


In [112]:
print(Trapecio_Compuesto(5,0,4))

Nodos: [0.  0.8 1.6 2.4 3.2 4. ] 
Pesos: [0.4 0.8 0.8 0.8 0.8 0.4] 


In [114]:
print(Lobato(3,0,5))

Nodos: [0.         1.38196601 3.61803399 5.        ] 
Pesos: [0.41666667 2.08333333 2.08333333 0.41666667] 


Veamos que integra correctamente:

In [98]:
x = sp.Symbol('x')
y=x**5
sp.integrate(y,(x,0,3))

243/2

In [99]:
f= lambda x: x**5

Legendre(3,0,3).Integrate(f)

121.50000000000003

In [100]:
Legendre(10,0,3).Integrate(f)

121.49999999999993

In [118]:
Trapecio_Compuesto(3,0,3).Integrate(f)

154.5

In [119]:
Lobato(3,0,3).Integrate(f)

121.50000000000003

In [120]:
Lobato(10,0,3).Integrate(f)

121.49999999999986

# Pasos que he seguido a la hora de construir las clases

## Legendre:
Los nodos y pesos de Legendre se obtienen directamente con la función

In [17]:
npl.leggauss(3)

(array([-0.77459667,  0.        ,  0.77459667]),
 array([0.55555556, 0.88888889, 0.55555556]))

## Lobato:
En la fórmula de Gauss_Lobato los nodos interiores son los ceros de la derivada del polinomio de Legendre $L_N'(x_i)=0$ y los pesos los he sacado de la fórmula del libro de Quarteroni.

In [41]:
n=2 #son n+1 puntos en total del x_0 al x_n

interior=legendre(n).deriv().r
nodos=[-1,*sorted(list(interior)),1]

pesos=2/(n*(n+1)*(legendre(n)(nodos))**2)

print(nodos,pesos)

[-1, 0.0, 1] [0.33333333 1.33333333 0.33333333]


In [43]:
legendre(3)(nodos)

array([-1.,  0.,  1.])

In [22]:
legendre(n)(nodos)

array([ 1. , -0.5,  1. ])

## Trapecios Compuestos:
En la fórmula de los trapecios he considerado el intervalo $(-1,1)$ en $n$ intervalos, de modo que tengo $n+1$ puntos, el incremento y por tanto h es, $h=\frac{b-a}n$ y los pesos en los extremos son $\frac h 2$ y en los nodos interiores $h$.

In [19]:
a,b=-1,1
n=6
[*np.arange(-1,1,float((b-a)/n)).tolist(),1] #nodos en Trapecios

[-1.0,
 -0.6666666666666667,
 -0.3333333333333335,
 -2.220446049250313e-16,
 0.33333333333333304,
 0.6666666666666663,
 1]

In [20]:
n=6 #x_0,...x_6 7 puntos
[2/(2*n),*[2/n]*(n-1),2/(2*n)] #pesos en Trapecios

[0.16666666666666666,
 0.3333333333333333,
 0.3333333333333333,
 0.3333333333333333,
 0.3333333333333333,
 0.3333333333333333,
 0.16666666666666666]

## Con Dani y Rafa Lunes 14 Marzo

In [21]:
class Cuadrature:
    def __init__(self,nodes=None,weight=None,num_points=None):
        if (nodes!=None and weight!=None):
            self.nodes = nodes
            self.weight = weight
            print(self.nodes,self.weight)
        elif(num_points!=None):
            self.nodes, self.weight= npl.leggauss(num_points)
            print(self.nodes,self.weight)
        else:
            raise Exception("No has metido correctamente los parámetros en la clase")
    def getNodes(self):
        return self.nodes
    def getWeight(self):
        return self.weight
    def Integrate(self,f):
        return self.Integrate_List(f(np.array(self.nodes)))
    def Integrate_List(self,lista):
        if (len(lista)==len(self.weight)):
            return np.array(lista).dot(np.array(self.weight))
        else:
            raise Exception("No has metido correctamente la lista")
        

In [22]:
Cuadrature(4)

Exception: No has metido correctamente los parámetros en la clase

In [25]:
cuad_gauss=Cuadrature(num_points=6)

[-0.93246951 -0.66120939 -0.23861919  0.23861919  0.66120939  0.93246951] [0.17132449 0.36076157 0.46791393 0.46791393 0.36076157 0.17132449]


In [26]:
f= lambda x: x**10
cuad_gauss.Integrate(f)

0.18181818181818124

In [27]:
lista=[2,4,5,0]
cuad_gauss.Integrate_List(lista)

Exception: No has metido correctamente la lista